# coding: utf-8

# flake8: noqa
"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.client_run_info import ClientRunInfo
from openapi_client.models.client_run_info_list import ClientRunInfoList
from openapi_client.models.client_task_info import ClientTaskInfo
from openapi_client.models.current_time import CurrentTime
from openapi_client.models.dres_admin_info import DresAdminInfo
from openapi_client.models.dres_info import DresInfo
from openapi_client.models.error_status import ErrorStatus
from openapi_client.models.login_request import LoginRequest
from openapi_client.models.query_event import QueryEvent
from openapi_client.models.query_event_log import QueryEventLog
from openapi_client.models.query_result import QueryResult
from openapi_client.models.query_result_log import QueryResultLog
from openapi_client.models.result_element import ResultElement
from openapi_client.models.run_result import RunResult
from openapi_client.models.success_status import SuccessStatus
from openapi_client.models.successful_submissions_status import SuccessfulSubmissionsStatus
from openapi_client.models.task_result import TaskResult
from openapi_client.models.user_details import UserDetails
