# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictInt, StrictStr

from typing import Optional

from dres_api.models.successful_submissions_status import SuccessfulSubmissionsStatus

from dres_api.api_client import ApiClient
from dres_api.api_response import ApiResponse
from dres_api.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class SubmissionApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def get_api_v1_submit(self, collection : Annotated[Optional[StrictStr], Field(description="Collection identifier. Optional, in which case the default collection for the run will be considered.")] = None, item : Annotated[Optional[StrictStr], Field(description="Identifier for the actual media object or media file.")] = None, text : Annotated[Optional[StrictStr], Field(description="Text to be submitted. ONLY for tasks with target type TEXT. If this parameter is provided, it superseeds all athers.")] = None, frame : Annotated[Optional[StrictInt], Field(description="Frame number for media with temporal progression (e.g. video).")] = None, shot : Annotated[Optional[StrictInt], Field(description="Shot number for media with temporal progression (e.g. video).")] = None, timecode : Annotated[Optional[StrictStr], Field(description="Timecode for media with temporal progression (e.g. video).")] = None, session : Annotated[Optional[StrictStr], Field(description="Session Token")] = None, **kwargs) -> SuccessfulSubmissionsStatus:  # noqa: E501
        """Endpoint to accept submissions  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_api_v1_submit(collection, item, text, frame, shot, timecode, session, async_req=True)
        >>> result = thread.get()

        :param collection: Collection identifier. Optional, in which case the default collection for the run will be considered.
        :type collection: str
        :param item: Identifier for the actual media object or media file.
        :type item: str
        :param text: Text to be submitted. ONLY for tasks with target type TEXT. If this parameter is provided, it superseeds all athers.
        :type text: str
        :param frame: Frame number for media with temporal progression (e.g. video).
        :type frame: int
        :param shot: Shot number for media with temporal progression (e.g. video).
        :type shot: int
        :param timecode: Timecode for media with temporal progression (e.g. video).
        :type timecode: str
        :param session: Session Token
        :type session: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: SuccessfulSubmissionsStatus
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_api_v1_submit_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_api_v1_submit_with_http_info(collection, item, text, frame, shot, timecode, session, **kwargs)  # noqa: E501

    @validate_arguments
    def get_api_v1_submit_with_http_info(self, collection : Annotated[Optional[StrictStr], Field(description="Collection identifier. Optional, in which case the default collection for the run will be considered.")] = None, item : Annotated[Optional[StrictStr], Field(description="Identifier for the actual media object or media file.")] = None, text : Annotated[Optional[StrictStr], Field(description="Text to be submitted. ONLY for tasks with target type TEXT. If this parameter is provided, it superseeds all athers.")] = None, frame : Annotated[Optional[StrictInt], Field(description="Frame number for media with temporal progression (e.g. video).")] = None, shot : Annotated[Optional[StrictInt], Field(description="Shot number for media with temporal progression (e.g. video).")] = None, timecode : Annotated[Optional[StrictStr], Field(description="Timecode for media with temporal progression (e.g. video).")] = None, session : Annotated[Optional[StrictStr], Field(description="Session Token")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Endpoint to accept submissions  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_api_v1_submit_with_http_info(collection, item, text, frame, shot, timecode, session, async_req=True)
        >>> result = thread.get()

        :param collection: Collection identifier. Optional, in which case the default collection for the run will be considered.
        :type collection: str
        :param item: Identifier for the actual media object or media file.
        :type item: str
        :param text: Text to be submitted. ONLY for tasks with target type TEXT. If this parameter is provided, it superseeds all athers.
        :type text: str
        :param frame: Frame number for media with temporal progression (e.g. video).
        :type frame: int
        :param shot: Shot number for media with temporal progression (e.g. video).
        :type shot: int
        :param timecode: Timecode for media with temporal progression (e.g. video).
        :type timecode: str
        :param session: Session Token
        :type session: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(SuccessfulSubmissionsStatus, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'collection',
            'item',
            'text',
            'frame',
            'shot',
            'timecode',
            'session'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_api_v1_submit" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('collection') is not None:  # noqa: E501
            _query_params.append(('collection', _params['collection']))

        if _params.get('item') is not None:  # noqa: E501
            _query_params.append(('item', _params['item']))

        if _params.get('text') is not None:  # noqa: E501
            _query_params.append(('text', _params['text']))

        if _params.get('frame') is not None:  # noqa: E501
            _query_params.append(('frame', _params['frame']))

        if _params.get('shot') is not None:  # noqa: E501
            _query_params.append(('shot', _params['shot']))

        if _params.get('timecode') is not None:  # noqa: E501
            _query_params.append(('timecode', _params['timecode']))

        if _params.get('session') is not None:  # noqa: E501
            _query_params.append(('session', _params['session']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "SuccessfulSubmissionsStatus",
            '202': "SuccessfulSubmissionsStatus",
            '400': "ErrorStatus",
            '401': "ErrorStatus",
            '404': "ErrorStatus",
            '412': "ErrorStatus",
        }

        return self.api_client.call_api(
            '/api/v1/submit', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
