# coding: utf-8

# flake8: noqa
"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from dres_api.models.client_run_info import ClientRunInfo
from dres_api.models.client_run_info_list import ClientRunInfoList
from dres_api.models.client_task_info import ClientTaskInfo
from dres_api.models.current_time import CurrentTime
from dres_api.models.dres_admin_info import DresAdminInfo
from dres_api.models.dres_info import DresInfo
from dres_api.models.error_status import ErrorStatus
from dres_api.models.login_request import LoginRequest
from dres_api.models.query_event import QueryEvent
from dres_api.models.query_event_log import QueryEventLog
from dres_api.models.query_result import QueryResult
from dres_api.models.query_result_log import QueryResultLog
from dres_api.models.result_element import ResultElement
from dres_api.models.run_result import RunResult
from dres_api.models.success_status import SuccessStatus
from dres_api.models.successful_submissions_status import SuccessfulSubmissionsStatus
from dres_api.models.task_result import TaskResult
from dres_api.models.user_details import UserDetails
