# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class DresAdminInfo(BaseModel):
    """
    DresAdminInfo
    """
    version: StrictStr = Field(...)
    start_time: StrictInt = Field(..., alias="startTime")
    uptime: StrictInt = Field(...)
    os: StrictStr = Field(...)
    jvm: StrictStr = Field(...)
    args: StrictStr = Field(...)
    cores: StrictInt = Field(...)
    free_memory: StrictInt = Field(..., alias="freeMemory")
    total_memory: StrictInt = Field(..., alias="totalMemory")
    load: Union[StrictFloat, StrictInt] = Field(...)
    available_sever_threads: StrictInt = Field(..., alias="availableSeverThreads")
    __properties = ["version", "startTime", "uptime", "os", "jvm", "args", "cores", "freeMemory", "totalMemory", "load", "availableSeverThreads"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DresAdminInfo:
        """Create an instance of DresAdminInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DresAdminInfo:
        """Create an instance of DresAdminInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DresAdminInfo.parse_obj(obj)

        _obj = DresAdminInfo.parse_obj({
            "version": obj.get("version"),
            "start_time": obj.get("startTime"),
            "uptime": obj.get("uptime"),
            "os": obj.get("os"),
            "jvm": obj.get("jvm"),
            "args": obj.get("args"),
            "cores": obj.get("cores"),
            "free_memory": obj.get("freeMemory"),
            "total_memory": obj.get("totalMemory"),
            "load": obj.get("load"),
            "available_sever_threads": obj.get("availableSeverThreads")
        })
        return _obj


