# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dres_api.api.log_api import LogApi  # noqa: E501


class TestLogApi(unittest.TestCase):
    """LogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LogApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_post_api_v1_log_query(self) -> None:
        """Test case for post_api_v1_log_query

        Accepts query logs from participants  # noqa: E501
        """
        pass

    def test_post_api_v1_log_result(self) -> None:
        """Test case for post_api_v1_log_result

        Accepts result logs from participants  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
