# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dres_api.api.batch_submission_api import BatchSubmissionApi  # noqa: E501


class TestBatchSubmissionApi(unittest.TestCase):
    """BatchSubmissionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BatchSubmissionApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_post_api_v1_submit_with_runid(self) -> None:
        """Test case for post_api_v1_submit_with_runid

        Endpoint to accept batch submissions in JSON format  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
