# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dres_api.models.dres_admin_info import DresAdminInfo  # noqa: E501

class TestDresAdminInfo(unittest.TestCase):
    """DresAdminInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DresAdminInfo:
        """Test DresAdminInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DresAdminInfo`
        """
        model = DresAdminInfo()  # noqa: E501
        if include_optional:
            return DresAdminInfo(
                version = '',
                start_time = 56,
                uptime = 56,
                os = '',
                jvm = '',
                args = '',
                cores = 56,
                free_memory = 56,
                total_memory = 56,
                load = 1.337,
                available_sever_threads = 56
            )
        else:
            return DresAdminInfo(
                version = '',
                start_time = 56,
                uptime = 56,
                os = '',
                jvm = '',
                args = '',
                cores = 56,
                free_memory = 56,
                total_memory = 56,
                load = 1.337,
                available_sever_threads = 56,
        )
        """

    def testDresAdminInfo(self):
        """Test DresAdminInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
