# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dres_api.api.status_api import StatusApi  # noqa: E501


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatusApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_status_info(self) -> None:
        """Test case for get_api_v1_status_info

        Returns an overview of the server properties.  # noqa: E501
        """
        pass

    def test_get_api_v1_status_info_admin(self) -> None:
        """Test case for get_api_v1_status_info_admin

        Returns an extensive overview of the server properties.  # noqa: E501
        """
        pass

    def test_get_api_v1_status_time(self) -> None:
        """Test case for get_api_v1_status_time

        Returns the current time on the server.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
