# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dres_api.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_logout(self) -> None:
        """Test case for get_api_v1_logout

        Clears all user roles of the current session.  # noqa: E501
        """
        pass

    def test_get_api_v1_user(self) -> None:
        """Test case for get_api_v1_user

        Get information about the current user.  # noqa: E501
        """
        pass

    def test_post_api_v1_login(self) -> None:
        """Test case for post_api_v1_login

        Sets roles for session based on user account and returns a session cookie.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
