# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.client_run_info_list import ClientRunInfoList  # noqa: E501

class TestClientRunInfoList(unittest.TestCase):
    """ClientRunInfoList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientRunInfoList:
        """Test ClientRunInfoList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientRunInfoList`
        """
        model = ClientRunInfoList()  # noqa: E501
        if include_optional:
            return ClientRunInfoList(
                runs = [
                    openapi_client.models.client_run_info.ClientRunInfo(
                        id = '', 
                        name = '', 
                        description = '', 
                        status = 'CREATED', )
                    ]
            )
        else:
            return ClientRunInfoList(
                runs = [
                    openapi_client.models.client_run_info.ClientRunInfo(
                        id = '', 
                        name = '', 
                        description = '', 
                        status = 'CREATED', )
                    ],
        )
        """

    def testClientRunInfoList(self):
        """Test ClientRunInfoList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
