# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.client_task_info import ClientTaskInfo  # noqa: E501

class TestClientTaskInfo(unittest.TestCase):
    """ClientTaskInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientTaskInfo:
        """Test ClientTaskInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientTaskInfo`
        """
        model = ClientTaskInfo()  # noqa: E501
        if include_optional:
            return ClientTaskInfo(
                id = '',
                name = '',
                task_group = '',
                remaining_time = 56,
                running = True
            )
        else:
            return ClientTaskInfo(
                id = '',
                name = '',
                task_group = '',
                remaining_time = 56,
                running = True,
        )
        """

    def testClientTaskInfo(self):
        """Test ClientTaskInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
