# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.client_run_info_api import ClientRunInfoApi  # noqa: E501


class TestClientRunInfoApi(unittest.TestCase):
    """ClientRunInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClientRunInfoApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_client_run_info_currenttask_with_runid(self) -> None:
        """Test case for get_api_v1_client_run_info_currenttask_with_runid

        Returns an overview of the currently active task for a run  # noqa: E501
        """
        pass

    def test_get_api_v1_client_run_info_list(self) -> None:
        """Test case for get_api_v1_client_run_info_list

        Lists an overview of all competition runs visible to the current client  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
