# coding: utf-8

"""
    DRES API

    API for DRES (Distributed Retrieval Evaluation Server), Version 1.0

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.submission_api import SubmissionApi  # noqa: E501


class TestSubmissionApi(unittest.TestCase):
    """SubmissionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubmissionApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_submit(self) -> None:
        """Test case for get_api_v1_submit

        Endpoint to accept submissions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
